# ui
font-family = "JetBrainsMono Nerd Font"
font-size = 12
font-style = Regular
background-opacity = 0.85
window-decoration = false
# maximize = true
# fullscreen = true
window-width = 185
window-height = 50
theme= Banana Blueberry
gtk-tabs-location = "hidden"
gtk-wide-tabs = false
copy-on-select = true

# has no effect on linux
window-save-state = "always" 

keybind = ctrl+shift+n=unbind
keybind = ctrl+shift+t=unbind
keybind = ctrl+shift+c=unbind
keybind = ctrl+shift+z=unbind
keybind = ctrl+r=unbind

# keybind
# grab history
# keybind = "ctrl+shift+h=write_screen_file:paste"
# keybind = "ctrl+shift+j=text:\x01hx +1000000 \n"
# keybind = "ctrl+h=goto_split:next"
# keybind = "ctrl+k=goto_split:previous"
# keybind = "super+ctrl+r=new_split:right"
# keybind = "super+ctrl+u=new_split:up"
# keybind = "ctrl+shift+arrow_up=resize_split:up,80"
# keybind = "ctrl+shift+arrow_down=resize_split:down,80"
# keybind = "ctrl+shift+arrow_left=resize_split:left,100"
# keybind = "ctrl+shift+arrow_right=resize_split:right,100"
# keybind = "ctrl+shift+n=next_tab"
# keybind = "ctrl+shift+m=previous_tab"
# keybind = "ctrl+shift+t=new_tab"

keybind = "super+ctrl+m=toggle_maximize"
keybind = "ctrl+shift+p=toggle_command_palette"
